version: "3.5"
services:
  sese:
    image: anzupop/sese-engine:latest
    # 你可能需要添加端口
    ports:
      - "80:80"
      - "14951:14951"
    restart: unless-stopped
    environment:
      # 你可能需要更改此处的代理
      https_proxy: http://127.0.0.1:10808
      http_proxy: http://127.0.0.1:10808
    # 你可能需要更改挂载的位置
    # volumes:
      # - "/tmp:/code/savedata"
