version: "3.5"
services:
  sese:
    image: jokereven/sese-engine:latest
    # 你可能需要添加端口
    ports:
      - "80:80"
      - "14951:14951"
    restart: unless-stopped
    environment:
      # 你可能需要更改此处的代理
      https_proxy: http://172.24.144.1:7890
      http_proxy: http://172.24.144.1:7890
    # 你可能需要更改挂载的位置
    # volumes:
      # - "/tmp:/home/sese"
