version: "3.5"
services:
  sese:
    image: anzupop/sese-engine:latest
    ports:
      - "4950:4950"
    restart: unless-stopped
    environment:
      # 你可能需要更改此处的代理
      HTTPS_PROXY: http://127.0.0.1:10808
    # 你可能需要更改挂载的位置
    volumes:
      - "/tmp:/code/savedata"
